### PR TITLE
Snarky polymorphic_record ppx

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR adds the `polymorphic_record` ppx structure to `ppx_snarky`. Currently, it takes a format

```ocaml
[%%polymorphic_record
 `Instances [T; Snarkable]
 , `Fields
     [ ("field1", Mod1); ("field2", Mod2); ("field3", Mod3) ]
 , `Contents
    [ `Fold ("f1", (+)); `Fold ("f2", ( * )) ]]
```

and generates

```ocaml
type ('mod1, 'mod2, 'mod3) polymorphic =
 { field1 : 'mod1; field2 : 'mod2; field3 : 'mod3 }
 
let field1 {field1; _} = field1
and field2 {field2; _} = field2
and field3 {field3; _} = field3

module T = struct
  type t = (Mod1.T.t, Mod2.T.t, Mod3.T.t) polymorphic
end
include T

module Snarkable = struct
  type t = (Mod1.Snarkable.t, Mod2.Snarkable.t, Mod3.Snarkable.t) polymorphic
  let typ = (* ... *)
  let f1 t = Mod1.Snarkable.f1 t.field1 + Mod2.Snarkable.f1 t.field2 + Mod3.Snarkable.f1 t.field3
  let f2 t = Mod1.Snarkable.f2 t.field1 * Mod2.Snarkable.f2 t.field2 * Mod3.Snarkable.f2 t.field3
end
```

The actual format in this PR supports slightly more options; see `ppx_snarky/examples/polyrecord.ml` a slightly more complex situation and `ppx_snarky/examples/polyrecord.pp.ml` for its output. Command to generate output (assuming that hex number doesn't change):

```bash
(pushd src; _build/default/.ppx/jbuild/6ef087b31a4c43bd4005df43cf3b1e72/ppx.exe -o lib/ppx_snarky/examples/polyrecord.pp.ml --impl lib/ppx_snarky/examples/polyrecord.ml; popd; make reformat)
```

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by psteckler** [comment]
In the posted example, why does `Snarkable` get `f1` and `f2`, but not `T`? Does the name `T` get special treatment?

**Comment by mrmr1993** [comment]
Thanks, that's great to hear!

> I think the next steps will be to look into how we can define custom generators for polymorphic record instances. Probably could implement something like what ppx_deriving does for interacting with different ppx drivers to generate code.

Sure, that sounds fairly straightforward, I'll try to get started on it soon.

-------------------------------------------------

Separately, I've been thinking a little about the syntax -- especially about how I might view it as a newcomer to snarky, after my last chat with @imeckler -- and I wondered if there was a way to make it a bit more OCaml-y. Does anybody have any thoughts on adding syntax along these lines:

```ocaml
[%%snarky_polymorphic
  [ `Module T
  ; `Module Snarkable
  ; let%polydef t = { x = X; y = (Y, Y.Checked); z = (Z, Z.Check.var) } in __
  ; `Fields t
  ; let%polytyp typ = ___ in Snarkable
  ; let%polyfold sum t = Mod.sum t.field + (___ + Mod.sum t.field) in Snarkable
  ; let%polyfold prod t = Mod.prod t.field * (___ * Mod.prod t.field) in T, Snarkable.checked_prod
  ; let%polyfold string t = String.concat (Mod.to_string t.field) (String.concat __ (Mod.to_string t.field)) in T
  ; `Include T ]]
```

expanding to

```ocaml
type ('x, 'y, 'z) polymorphic = { x : 'x; y : 'y; z : 'z }
let x {x; _} = x
let y {y; _} = y
let z {z; _} = z

module T = struct
  type t = (X.T.t, Y.t, Z.t) polymorphic
  let prod t = X.prod t.x + (Y.prod t.y + Z.prod t.z)
  let string t = String.concat (X.to_string t.x (String.concat (Y.to_string t.y) (Z.to_string t.z)))
end

module Snarkable = struct
  type t = (X.Snarkable.t, Y.Checked.t, Z.Check.var) polymorphic
  let typ = (* ... *)
  let sum t = X.Snarkable.sum t.x + Y.Checked.sum t.y + Z.Check.sum t.z
  let checked_prod t = X.Snarkable.prod t.x * Y.Checked.prod t.y * Z.Check.prod t.z
end

include T
```

**Comment by psteckler** [comment]
> It's just the order: the first name gets treated as the normal-type module, and the second as the snark-type module.

Is the number of module names limited to 2? Is it useful to have more than 2, which all share the poly record, but differ in their functions? Not sure if there's a use case, just wondering ...

**Comment by mrmr1993** [comment]
> Is the number of module names limited to 2?

It is at the moment. Do you have any ideas for syntax? I was hoping that the one I proposed above would allow for this, but we decided at the snarky meeting that it was too verbose.

**Comment by mrmr1993** [comment]
I've reworked this based on everyone's feedback. I think I've covered everything that everybody asked for; please let me know if I've missed anything.

Syntax is now:

```ocaml
[%snarky_module
  let%polydef polymorphic = {some= Some; field= Field; names= Names; here= Here}
  [%%polyfields polymorphic]
  [%%poly type t = polymorphic]

  [%%snarkytyp (typ : polymorphic Typ.t)] (* Explicit Typ.t, since we can't infer where it will be in cases like Tick.Typ.t etc. *)

  module Var = struct
    [%%poly type t = polymorphic]
    let%polyfold length_in_bits = Pervasives.(+)
    let%polyfold fold t = Fold_lib.( +> )
  end]
```

Most notable changes are:
* the `snarky_module` ppx can contain any other valid OCaml in any other location
* it's possible to write another ppx to generate some of the `let%polyfold ... = ...` statements and run it before this ppx, to reduce the boilerplate more
* all of the sub extensions are optional (although they need a `polydef` to work correctly), so it's easy to e.g. just declare a polymorphic type and generate the `Typ.t`.

See [examples/snarky_module.ml](https://github.com/CodaProtocol/coda/pull/1389/files#diff-7905ae7b193a90dc4e8b6d5efd630acf) and [examples/snarky_module.pp.ml](https://github.com/CodaProtocol/coda/pull/1389/files#diff-543bc798a302093febc1628dacce8d0a) for an example/testcase. Example `.pp.ml` file is now compiled with `(pushd src; dune exec .ppx/ppx_snarky/ppx.exe -- -o lib/ppx_snarky/examples/snarky_module.pp.ml --impl lib/ppx_snarky/examples/snarky_module.ml; popd; make reformat)`

**Pull request merged**
