### PR TITLE
Website redesign/leaderboard reskin

### PR DESCRIPTION
**Pull request by michellewong793**
Reskins the Leaderboard and Member Profile page.

LB: 
image

MP: 
Screen Shot 2020-09-22 at 4 06 37 PM

https://www.figma.com/file/vyGC2DCKTBFDR6HIkHt6sK/Testworld?node-id=2650%3A0]]

Screen Shot 2020-09-21 at 5 26 31 PM

### CODE REVIEW

**Comment by MartinMinkov** [comment]
Currently getting this on the leaderboard. D: 
image

**Comment by MartinMinkov** [comment]
I think the buttons and the data labels should be horizontally centered. 
image

**Comment by MartinMinkov** [comment]
The labels and the buttons should be vertically aligned
image

**Comment by MartinMinkov** [comment]
I think the ranks should be vertically centered :) 
image

**Comment by michellewong793** [comment]
> Currently getting this on the leaderboard. D:
> image

image

**Comment by michellewong793** [comment]
> I think the buttons and the data labels should be horizontally centered.
> image

Screen Shot 2020-09-23 at 1 23 53 PM
woo!

**Review by MartinMinkov — APPROVED** [review]
lgtm! :+1:

**Pull request merged**
