### PR TITLE
SIMPLE:expand with-balances to with-details

### PR DESCRIPTION
**Pull request by jkrauska**
We need a quick way to collect nonce summaries.
expanding -with-balances to -with-details (including balances and nonces) was an easy way to accomplish this.

New format:

```
coda.exe advanced get-pub -with-details
8QnLYnzAkhx3moXHHBBpK418LGCEiQZzYDgKggntsNkZqsUJLFos474Mzoy5mWJP9S, 10000000, 0
8QnLTHMZPbBFezS8j8kDPu6iLiwPsTPyX2vMwcFzjiDZbp6GQDEBEyLbYvzApSdTsE, 100, 0
8QnLWWJ33Wm1e4ejaMeYC6RsjpaodiVuYY3RzKZ3ys5UBAmpaupV1SD6LSU2a6KB3L, 1000, 0
8QnLZ1fit1QXTLiFPcSuaR4F7ySgDMK2ZHpDLZU8Jm2ABE1K9n2Fbswme9SaSTd8bJ, 1000, 0
8QnLYLvy4FLKVo3qt9A32yLRLyEFHqf5NZTTFynajH6gNMH3AR4HA2gZTju8NpCgDU, 1000, 0
8QnLTkPLvGe1nAjtLP6WQzaVw2VKxQ9pAPLRPMd3eVbkfUuUL7g4R7mFrzuTZQgByc, 1000, 0
8QnLTnAYna24EdfX9dDMstUtWnQqU39YQBS4G7PjJD2KjQVHKZEhrPDeNSLJFrKiyr, 1000, 0
8QnLYGKxLpHq3BLEBzJSD83meqaTExGZRtMGqYnptPhMtXxauSaq2xFw9GGZgr2gRL, 1000, 0
8QnLWA5QDK8QmBSoJBZqDFDw2DDdnoTqsrbMk5XhfssWKWjuwv4devH96vM93mhx2M, 1000, 0
8QnLXHMwqYs1EbsAZGW7kWypUno6gThzXPFB68h4RMTGjABJa6byqKC4cSzRvNuezj, 1000, 0
8QnLVn7EEPcPYC36TqtdE7orCnsUXZuq2ZNRxEFFNPzB16XzesDFknDifFGuSHXYzJ, 1000, 0
8QnLVLAosnB4F8V5NFmnKpaq1cwK2Rxfx3BbpPSNLUpC4ZKgwcPdzTUYNFmDjV1tC2, 1000, 0
8QnLVwUvKfjSrbnMvyN7Aug2dPVoZgQW2SxiPrjUuTtVem6yidXzd2jtm9rsLBkBoE, 1000, 0
8QnLV2Jzyk2CVvTxYm2FUMqkwN82UEQsqtTSpYZ28TAcs3bbPXmGocFXfbNtfourse, 1000, 0
8QnLVvGkxs7gRepXjpoZwvdJTo4nx163Edd86jaxqRwkN5PZFdHReHBf7Gz89JfBnW, 1000, 0
8QnLTa5HrkCFbG5iFKpkjygJ7jYbms1TyBAkPJCpHV8rCGTxGt49DGzYZoxjVjt6kC, 1000, 0
8QnLUPQhCoLAfXdN5uxgFicmHGj12Ew9RCafxW6UwUeJxqKdQ6KdTSV7j2jKs67jZB, 1000, 0
8QnLU5Qbfr2tp37R5EMjBBBwC9R1S8dwePDYJTfmuHD6sVNKgE4JRmF8DPYAVH4V5s, 1000, 0
```

and in json
```
coda.exe advanced get-pub -with-details -json | head -n 030
{
  "accounts": [
    {
      "key":
        "8QnLYnzAkhx3moXHHBBpK418LGCEiQZzYDgKggntsNkZqsUJLFos474Mzoy5mWJP9S",
      "balance": 10000000,
      "nonce": 0
    },
    {
      "key":
        "8QnLTHMZPbBFezS8j8kDPu6iLiwPsTPyX2vMwcFzjiDZbp6GQDEBEyLbYvzApSdTsE",
      "balance": 100,
      "nonce": 0
    },
    {
      "key":
        "8QnLWWJ33Wm1e4ejaMeYC6RsjpaodiVuYY3RzKZ3ys5UBAmpaupV1SD6LSU2a6KB3L",
      "balance": 1000,
      "nonce": 0
    },
    {
      "key":
        "8QnLZ1fit1QXTLiFPcSuaR4F7ySgDMK2ZHpDLZU8Jm2ABE1K9n2Fbswme9SaSTd8bJ",
      "balance": 1000,
      "nonce": 0
    },
...
```

### CODE REVIEW

**Comment by wu-s-john** [comment]
Looks good so far, but can you show how the output looks like as a comment?

**Comment by nholland94** [comment]
I think you could have gone even further and dumped the entire account record, but this still looks good for getting the nonce in.

**Comment by cmr** [comment]
Should `get-public-keys` be merged with `dump-ledger`? They're starting to overlap a lot.

**Comment by jkrauska** [comment]
> Should `get-public-keys` be merged with `dump-ledger`? They're starting to overlap a lot.

@cmr  I couldn't get dump-ledger to work without a staged ledger hash. (I think you fixed that)

if you can easily unify and provide json, go for it, if not I'm ok with this as a stopgap.

**Comment by cmr** [comment]
Paul fixed it in https://github.com/CodaProtocol/coda/pull/3038, which wasn't merged in time for the current net but should be good to go for the next one. `coda advanced dump-ledger -json` should work.

**Pull request merged**
