### PR TITLE
increase depth to 30

### PR DESCRIPTION
**Pull request by imeckler**
This increases the ledger depth to 30

### CODE REVIEW

**Comment by cmr** [comment]
Is this now failing just because the SNARK takes longer? @es92?

**Comment by cmr** [comment]
Hm, no, the integration tests don't run with SNARKs...

**Comment by cmr** [comment]
Catchup "startup time" tripled, and somehow we're only getting off less than a dozen sync_ledger queries over 4 seconds. Is this another symptom of wonky scheduler interaction? Why are ledger sync queries being generated and/or serviced so slowly?

**Comment by cmr** [comment]
I don't think the proposal interval is being respected correctly, in that branch I'm seeing `Broadcasting (New_state` every 1.3-2ish seconds. Not the 10 I expect.

**Comment by cmr** [comment]
Because it's looking at the `transition_interval`. Ok, fine.

**Comment by cmr** [comment]
Yes. Not sure where.

**Comment by cmr** [comment]
Ok, cranking up the `transition_interval` defaults everywhere to 10s gives enough time for the new node to actually catch up and the test to succeed.

**Comment by jkrauska** [comment]
@cmr if depth 30 is too tricky now, can we try 16? 12?

**Comment by cmr** [comment]
sorry for hijacking your PR, and the delay. but things should be better now. integration tests now take ~twice as long.

**Comment by cmr** [comment]
Just a note: this changes `env OMP_NUM_THREADS=6 /usr/bin/time ./_build/default/src/app/cli/src/coda.exe integration-tests transaction-snark-profiler` results from

```
Total time was: 26.449s
205.71user 1.38system 1:04.64elapsed 320%CPU (0avgtext+0avgdata 1007636maxresident)k
0inputs+0outputs (0major+1196632minor)pagefaults 0swaps
```

to

```
Total time was: 34.178s
296.72user 1.99system 1:32.17elapsed 324%CPU (0avgtext+0avgdata 1247768maxresident)k
0inputs+0outputs (0major+1931643minor)pagefaults 0swaps
```

on my machine.

**Pull request merged**
