### PR TITLE
Hack: DO NOT propose until it sync'd with the network

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
The proposer has trouble doing bootstrap, see #2642. This is a hack to make the proposer wait for `k` slots to make sure that it would be synced before trying to propose.

The proper change would require us to do some kind of bootstrap eagerly before start the proposer. I still need some time to think about the changes needed to be done.

### CODE REVIEW

**Comment by jkrauska** [comment]
so on initial turnup, all proposers must wait k slots before trying to propose anything?

**Comment by jkrauska** [comment]
> so on initial turnup, all proposers must wait k slots before trying to propose anything?

on our testnets k=6, so you'd have to wait 3 minutes to begin creating any blocks?

**Comment by jkrauska** [comment]
"In mainnet k should be significantly larger, it is spec'd at 2160 in OP."

**Comment by cmr** [comment]
I don't like it, but it's a decent workaround for now. @jkrauska presumably you're prepared to pass `-from-genesis` the first time the testnet runs proposers, and not afterwards?

**Pull request merged**
