### PR TITLE
Add diagram for high level daemon architecture

### PR DESCRIPTION
**Pull request by nholland94**
New diagram for the high level componetized architecture of our daemon. I will add some more detailed diagrams for some of the components and put together a single architecture markdown file as an entry point to all of these. In the diagram I made, the boxes on the left represent the external network interactions. There is a lot of whitespace on the bottom right hand side of the graph, but this is the best I was able to get the graph to look for now. I think it still looks pretty good for a computer generated graph.

### CODE REVIEW

**Comment by enolan** [comment]
Transaction pool should be connected to proposer

**Comment by bkase** [comment]
I can think of 3 things missing: (1) Transaction database (2) receipt chain database (3) wallets database.

@johnwu93 can you talk about how Transaction database and receipt chain database connects to the rest of the components.

"Wallets" database just talks to the file system and the API, and isn't connected to any other components

**Comment by jkrauska** [comment]
See also #1449 ?

**Comment by nholland94** [comment]
> See also #1449 ?

Yes, this is really a redo of that work @bkase and I did earlier in the year. I will close that one as it is no longer relevant and is very out of date.

**Comment by johnwu93** [comment]
1) Transaction Database
There is an extension (which is actually an incremental variable) that represents a new block. Whenever this variable gets updated, it adds the transactions of the block into the Transaction_database. So there should be an edge from Transition_frontier_extensions to Transaction_database. Also, the API makes queries to the transaction database. So, there should be an edge from API to Transaction_database

2) Receipt Chain Database
Whenever a transaction is sent via GraphQL or the cli, the transaction gets added to Receipt_chain_database. Maybe there should be an edge from Protocol to Receipt Chain Database and an edge from API to Receipt Chain Database

3) Wallet Database
Graphql directly talks to the Wallet Database to make queries or updates to the Wallet. So there should be an edge from API to Wallet Database

**Pull request closed without merging**
