### PR TITLE
Build snarky into the docker instance

### PR DESCRIPTION
**Pull request by mrmr1993**
This PR builds snarky into the docker instance with `PERFORMANCE=on`.

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by cmr** [comment]
To actually update the containers, you need to `make toolchains` followed by `make update-deps`. This takes a while and uses a lot of bandwidth...

**Comment by enolan** [comment]
I'd prefer, as a general principle, that we pin a specific git commit as
opposed to whatever the latest version in a given branch is.

**Comment by mrmr1993** [comment]
@enolan the idea of the `coda` branch is that it tracks the latest commit that is confirmed to work with coda. In effect, using that branch should be the same as manually specifying the commit each time.

**Comment by enolan** [comment]
What I want is for building a checkout of the Coda to always output the
same thing. If we're pulling in the tip of a branch somewhere, it'll be
inconsistent and we may get bugs or changes in behavior appearing seemingly
out of nowhere. This is especially bad if Snarky changes in a backwards
incompatible way.

**Pull request closed without merging**
