### PR TITLE
Unit test to compare update, update_var results

### PR DESCRIPTION
**Pull request by psteckler**
Wrote a unit test to compare results from `update` and `update_var` in proof-of-stake `Conensus_state`.

The test is in the `Quickcheck` monad, to make use of the consensus state generator. There's a computation in the `Snark.Checked` monad, which contains the `assert` to compare results. There's no `equal` for the type being compared, and maybe there's a reason for that, so I used polymorphic equality. Mea culpa.

Update:

Instead of using Quickcheck to gen a state, the test starts from the genesis state, which allows us to use the genesis ledger, which is used to produce a sparse ledger used with a `Tick` handler. We also put the snark-world result back in the value world, allowing us to use `equal_value` instead of polymorphic equality.

The strategy in the test is:

  - create arguments for `update`
  - apply `update`
  - convert those arguments to the `var`/snarked world
  - apply `update_var`
  - compare results

- [X] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by cmr** [comment]
I admit I'm a bit surprised the polymorphic equality succeeds. I thought there was some GMP stuff in there that would throw it off...

**Comment by psteckler** [comment]
I started to add a deriving `eq`, but it was reaching code that I wasn't sure should have `eq`, like in `Snark_bits`.

**Comment by cmr** [comment]
The polymorphic equality isn't succeeding. This builds a checked computation and a quickcheck generator, but doesn't run either of them. The missing piece:

```diff
diff --git a/src/lib/consensus/proof_of_stake.ml b/src/lib/consensus/proof_of_stake.ml
index e9d42261..2db17c24 100644
--- a/src/lib/consensus/proof_of_stake.ml
+++ b/src/lib/consensus/proof_of_stake.ml
@@ -1572,8 +1572,8 @@ let%test_module "Proof of stake tests" =
 
     let%test_unit "update, update_var agree starting from same consensus state"
         =
-      ignore
-        (let open Quickcheck.Let_syntax in
+      let gen =
+        let open Quickcheck.Let_syntax in
         (* build pieces needed to apply "update" *)
         let gen_slot_advancement = Core.Int.gen_incl 1 10 in
         let%bind make_consensus_state =
@@ -1609,8 +1609,8 @@ let%test_module "Proof of stake tests" =
           |> Or_error.ok_exn
         in
         (* build pieces needed to apply "update_var" *)
-        ignore
-          (let open Snark_params.Tick in
+        let checked_computation =
+          let open Snark_params.Tick in
           let open Let_syntax in
           (* work in Checked monad *)
           let%bind previous_state =
@@ -1641,9 +1641,12 @@ let%test_module "Proof of stake tests" =
           in
           (* please forgive use of polymorphic equality *)
           assert (new_state_var = new_consensus_state_var) ;
-          return ()) ;
-        return ()) ;
-      ()
+          return ()
+        in
+        assert (Crypto_params.Tick0.check checked_computation ()) ;
+        return ()
+      in
+      Quickcheck.test gen ~f:(fun () -> ())
   end )
 
 [%%endif]
```

**Comment by psteckler** [comment]
Thanks for catching that silly error.

I'll see if I can make a valid equality check.

**Comment by psteckler** [comment]
In fact, the `check` fails, with the polymorphic equality assert removed.

**Pull request merged**
