### PR TITLE
Status shows the highest block length encountered

### PR DESCRIPTION
**Pull request by wu-s-john**
We keep a record of the most recent transition that has been proof-validated. We compute the blockchain length of that transition. This will give us an indication of how synced a node is to the network

Ran `dune exec coda client status` and it showed this:

```
Coda Daemon Status 
-----------------------------------

Maximum Block Length Encountered from a Valid Block:  1
Local Uptime:                                         53s
GIT SHA1:                                             [DIRTY]a1a7bc64c5448f4b96737daf9cd50fd826fdbb14
Configuration Directory:                              /Users/johnwu/.coda-config
Peers:                                                Total: 0 ()
User_commands Sent:                                   0
Snark Worker Running:                                 false
Sync Status:                                          Bootstrap
Proposers Running:                                    Total: 0 ()
Consensus Time Now:                                   12989:71
Consensus Mechanism:                                  proof_of_stake
Consensus Configuration:                              
    delta = 3
    k = 24
    c = 8
    c_times_k = 192
    slots_per_epoch = 576
    slot_duration = 2000
    epoch_duration = 1152000
    acceptable_network_delay = 6000

```

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by psteckler** [comment]
RFC 0018 says "blockchain length" -- can we use that wording?

**Comment by nholland94** [comment]
> RFC 0018 says "blockchain length" -- can we use that wording?

+1 for this. The wording as of right now is very verbose.

**Comment by wu-s-john** [comment]
@nholland94. We are actually this information for both the normal transition frontier phase and bootstrap. This transition does not actually have to enter the transition frontier. We want to track it because it gives us a good metric of how synced we are to the network. When we are in the normal transition frontier phase, it would like to have a good indicator if we are falling behind the network. When we get a new transition, we can compare the blockchain length of that transition and compare it with the frontier's best tip. This can tell us if we need to do ledger catchup or not, which can take a bit of time.

Likewise, for bootstrapping, seeing the best-seen transition will tell us how many blocks to be synced with the network.

**Comment by nholland94** [comment]
I still think this is a bad metric because it can give false information regarding synchronization to the network. For instance, imagine if a node has its time off sync. This metric will still reflect they are synced even when they are rejecting transitions because they aren't in the right time window. When we start worrying about adversaries, this metric becomes even more questionable. I'm fine to approve for now, but we need to determine a better way to provide this metric long term.

**Pull request merged**
