### PR TITLE
Updating pooled user commands CLI help text

### PR DESCRIPTION
**Pull request by garethtdavies**
The behavior of this command has changed but the help text still indicates the prior behavior (that only tx submitted by the daemon are included in the output). Now, this command will return all transactions in the mempool.

I'm not sure if the website text is autogenerated so I manually made the change there too.

Signed-off-by: Gareth Davies <hello@garethtdavies.com>

### CODE REVIEW

**Comment by mrmr1993** [comment]
Good catch, thanks!

**Comment by bkase** [comment]
@garethtdavies I don't have push access to your fork so I can't fix this for you, but would you mind running `make reformat`? The pretty-printer lint is blocking the PR.

**Comment by garethtdavies** [comment]
> @garethtdavies I don't have push access to your fork so I can't fix this for you, but would you mind running `make reformat`? The pretty-printer lint is blocking the PR.

I think that should sort it. FWIW I do have the allow edits for maintainers checked and I've seen this before myself and was an authentication issue i.e. adding my remote via https vs ssh or it could be related to authenticating via the API vs an SSH key. Either way, it's likely some combination of that but adding remotes to solve these sorts of issues is usually painful vs. having it done automatically via CI.

CleanShot 2020-07-15 at 14 07 23@2x

**Comment by bkase** [comment]
> FWIW I do have the allow edits by maintainers checked and I've seen this before myself and was an authentication issue i.e. adding the contributor's remote via https vs ssh or it could be related to authenticating via the API vs an SSH key. Either way, it's likely some combination of that but adding remotes to solve these sorts of issues is usually painful vs. having it done automatically via CI.

Weird -- I tried `git remote add gareth git@github.com:garethtdavies/coda.git` but couldn't push to your branch, am I doing it wrong?

**Comment by garethtdavies** [comment]
> Weird -- I tried `git remote add gareth git@github.com:garethtdavies/coda.git` but couldn't push to your branch, am I doing it wrong?

That _should_ work. Are you authenticating to GitHub via the API or an SSH key?

**Comment by garethtdavies** [comment]
Oh, you did push to it, so something worked :)

**Pull request merged**
