### PR TITLE
Created set staking cli command

### PR DESCRIPTION
**Pull request by wu-s-john**
propose_public_keys now returns the most recently set public keys in proposer agent

You can validate the correctness of this command by doing the following:

1. Start daemon
```
dune exec coda daemon -- -rest 1337
```

2. Check that you have no proposers
```
dune exec --profile=test_postake_catchup coda client status
```

```
Coda Daemon Status 
-----------------------------------

Global Number of Accounts:                     18
The Total Number of Blocks in the Blockchain:  1
Local Uptime:                                  36s
Ledger Merkle Root:                            292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207
Staged-ledger Hash:                            ((non_snark((ledger_hash 292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207)(aux_hash"\2404\236\246h\245\2481q*<g7\1698qJ\219\240\183~\207[\n\026\143J*\243d<u0")(pending_coinbase_aux"_\236\235f\255\200o8\217Rxlmily\194\219\1949\221N\145\180g)\215:'\251W\233")))(pending_coinbase_hash 108655325255570801863939104057111968723742021454441429835282958620845049836181193308858413))
Staged Hash:                                   248000002021266663831544818984017050139339677857197398355426830168173504852592939643760789
GIT SHA1:                                      [DIRTY]6cf16911a7ac3648be920ac05e5978090aad197f
Configuration Directory:                       /Users/johnwu/.coda-config
Peers:                                         Total: 0 ()
User_commands Sent:                            0
Snark Worker Running:                          false
Sync Status:                                   Offline
Proposers Running:                             Total: 0 ()
Best Tip Consensus Time:                       0:0
Consensus Time Now:                            11542:461
Consensus Mechanism:                           proof_of_stake
Consensus Configuration:                       
    delta = 3
    k = 24
    c = 8
    c_times_k = 192
    slots_per_epoch = 576
    slot_duration = 2000
    epoch_duration = 1152000
    acceptable_network_delay = 6000
```

3. Create new wallet via graphql and use the generated public as your proposing key

```
mutation {addWallet{publicKey}}
```

```
{
  "data": {
    "addWallet": {
      "publicKey": "8QnLUNW7sUxnApau4SLShwr25koiSKrECxtveu89PPmQW5pEyy3xK8YgRpZQkZEanc"
    }
  }
}
```

4. Set staking keys

```
 dune exec client set-staking -- [PUBLIC_KEYS]
```

```
New staking public keys : [8QnLUNW7sUxnApau4SLShwr25koiSKrECxtveu89PPmQW5pEyy3xK8YgRpZQkZEanc]
```

5. Check that you are now proposing with the new keys:

```
Coda Daemon Status 
-----------------------------------

Global Number of Accounts:                     18
The Total Number of Blocks in the Blockchain:  1
Local Uptime:                                  1100s
Ledger Merkle Root:                            292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207
Staged-ledger Hash:                            ((non_snark((ledger_hash 292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207)(aux_hash"\2404\236\246h\245\2481q*<g7\1698qJ\219\240\183~\207[\n\026\143J*\243d<u0")(pending_coinbase_aux"_\236\235f\255\200o8\217Rxlmily\194\219\1949\221N\145\180g)\215:'\251W\233")))(pending_coinbase_hash 108655325255570801863939104057111968723742021454441429835282958620845049836181193308858413))
Staged Hash:                                   248000002021266663831544818984017050139339677857197398355426830168173504852592939643760789
GIT SHA1:                                      [DIRTY]6cf16911a7ac3648be920ac05e5978090aad197f
Configuration Directory:                       /Users/johnwu/.coda-config
Peers:                                         Total: 0 ()
User_commands Sent:                            0
Snark Worker Running:                          false
Sync Status:                                   Offline
Proposers Running:                             Total: 1 (8QnLUNW7sUxnApau4SLShwr25koiSKrECxtveu89PPmQW5pEyy3xK8YgRpZQkZEanc)
Best Tip Consensus Time:                       0:0
Consensus Time Now:                            11543:454
Consensus Mechanism:                           proof_of_stake
Consensus Configuration:                       
    delta = 3
    k = 24
    c = 8
    c_times_k = 192
    slots_per_epoch = 576
    slot_duration = 2000
    epoch_duration = 1152000
    acceptable_network_delay = 6000
```
Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by Schmavery** [comment]
This is cool but requires using a combination of graphql and cli to accomplish this, can we instead have the user pass a list of private key filepaths similar to the other cli commands?

**Comment by wu-s-john** [comment]
With the comments, this is how I verfied that the `set_staking` command is working correctly:

- `dune exec --profile=test_postake_catchup coda client generate-keypair -- -privkey-path ~/Desktop/privkey`
`Public key: 8QnLXFyuFfc4BCoL85vde6ZBTW8SrRxTwue4YiDV8Q3W37nu2H2iCAe6bw4j2VpFPe`

- `dune exec --profile=test_postake_catchup coda client set-staking -- ~/Desktop/privkey`
```
Secret key password: 
New staking public key : 8QnLXFyuFfc4BCoL85vde6ZBTW8SrRxTwue4YiDV8Q3W37nu2H2iCAe6bw4j2VpFPe
```
- `dune exec --profile=test_postake_catchup coda client status `

```
Coda Daemon Status 
-----------------------------------

Global Number of Accounts:                     18
The Total Number of Blocks in the Blockchain:  1
Local Uptime:                                  270s
Ledger Merkle Root:                            292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207
Staged-ledger Hash:                            ((non_snark((ledger_hash 292462133461332458159171981562983904296145701941467300852132406174832024409812989016966207)(aux_hash"\2404\236\246h\245\2481q*<g7\1698qJ\219\240\183~\207[\n\026\143J*\243d<u0")(pending_coinbase_aux"_\236\235f\255\200o8\217Rxlmily\194\219\1949\221N\145\180g)\215:'\251W\233")))(pending_coinbase_hash 108655325255570801863939104057111968723742021454441429835282958620845049836181193308858413))
Staged Hash:                                   248000002021266663831544818984017050139339677857197398355426830168173504852592939643760789
GIT SHA1:                                      [DIRTY]6cf16911a7ac3648be920ac05e5978090aad197f
Configuration Directory:                       /Users/johnwu/.coda-config
Peers:                                         Total: 0 ()
User_commands Sent:                            0
Snark Worker Running:                          false
Sync Status:                                   Offline
Proposers Running:                             Total: 1 (8QnLXFyuFfc4BCoL85vde6ZBTW8SrRxTwue4YiDV8Q3W37nu2H2iCAe6bw4j2VpFPe)
Best Tip Consensus Time:                       0:0
Consensus Time Now:                            11904:515
Consensus Mechanism:                           proof_of_stake
Consensus Configuration:                       
    delta = 3
    k = 24
    c = 8
    c_times_k = 192
    slots_per_epoch = 576
    slot_duration = 2000
    epoch_duration = 1152000
    acceptable_network_delay = 6000
```

I've decided that we should only set only one keypair with this command. I think the UI experience would not be too user-friendly if the cli asks for multiple passwords.

**Comment by Schmavery** [comment]
I think the call to make it only support a single key for usability is great, thanks. We'll handle this all differently in the next version of the cli and it's pretty rare for now.
The cli stuff looks good, if someone wants to double-check the rpc stuff we're probably good to merge

**Comment by bkase** [comment]
rpc stuff looks good

**Pull request merged**
