### PR TITLE
Set up a Nix cache for the Mac builds

### PR DESCRIPTION
**Pull request by enolan**
Set up a Nix binary cache on S3. Mac build times go from 1h01m to 19m, and the cache won't become broken every time nixpkgs changes. The new paths will be built and added to S3, and future builds will be fast.

We can start using Nix for getting Kademlia on Linux too, rather than having the docker images + .deb packages, but that's a problem for another day.

Tested by running the build, changing something, seeing that it cached the dependencies, then running it again after changing nothing and seeing it cached the whole thing.

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by bkase** [comment]
🎉

**Comment by jkrauska** [comment]
Clarification: I think this means we're pinned on current NIX settings, right?? (at some point we need to assume nix updates are 'good')...

**Comment by jkrauska** [comment]
Can we include a method to rebuild/refresh cache with current best from nix?

**Comment by enolan** [comment]
Pinning `nixpkgs` is orthogonal to whether we have our own binary cache or not. This PR doesn't pin.

**Comment by bkase** [comment]
It looks like the nix part is ~3min slower than with the circleci cache (back when it worked). Given that it continually breaks, I'm still down with this approach instead.

> copying path '/nix/store/yaadsl6mnpkpp2fzgrvwq9vnmpc11r83-hpack-0.31.1' from 's3://o1-nix-cache'...
> warning: you did not specify '--add-root'; the result might be removed by the garbage collector

Does this warning matter?

**Comment by enolan** [comment]
The warning is fine. The result of the weird hack to cache build dependencies might be garbage collected, but that's talking about the local store, not the cache. And the local store is deleted when the vm terminates.

I uploaded a new commit that should make things faster in the no-new-work case.

**Comment by enolan** [comment]
Not uploading to the cache when we haven't built anything saves only about 30s. I think most of the time increase comes from us compiling a bunch of OCaml dependencies. Something broke with the OPAM cache, but I can't tell what. See [logs](https://circleci.com/gh/CodaProtocol/coda/49716?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), see for `make ctypes-base`.

**Pull request merged**
