### PR TITLE
Reject if there have been empty epochs since genesis

### PR DESCRIPTION
**Pull request by mrmr1993**
This logic was inconsistent with the snark, and would result in a
constraint-system failure if the first block after genesis was more than
an epoch later.

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by imeckler** [comment]
Should we have an error message explaining what's up?

**Comment by mrmr1993** [comment]
> Should we have an error message explaining what's up?

I think the empty epoch error that this raises might be good enough, but I can add a dedicated one if you think we should?

**Comment by psteckler** [comment]
Will there be related issues with empty epochs after a hard fork?

**Comment by mrmr1993** [comment]
> Will there be related issues with empty epochs after a hard fork?

There will have to be changes here, yes. This particular change isn't relevant though.

**Pull request merged**
