### PR TITLE
Disable LFS checkout for non-frontend CI jobs

### PR DESCRIPTION
**Pull request by mrmr1993**
This should fix CI, and reduce the burden on our GitHub LFS quota

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by mrmr1993** [comment]
As is, this dumps a ton of error messages on checkout, but it does successfully skip the LFS files :man_shrugging:

**Comment by bkase** [comment]
It still fails some of the steps though https://app.circleci.com/pipelines/github/CodaProtocol/coda/22664/workflows/82ecfe7f-f568-48b1-96c9-f57d584b46f5/jobs/428537/steps

**Comment by mrmr1993** [comment]
Updated to see if we can fix the Mac build

**Comment by mrmr1993** [comment]
> see if we can fix the Mac build

Nope :/

**Comment by mrmr1993** [comment]
Mac build now also succeeds at checkout.

**Pull request merged**
