### PR TITLE
CLI command snark-hashes in internal group

### PR DESCRIPTION
**Pull request by psteckler**
New CLI command `internal snark-hashes [-json]`.

Lists the unique hex strings/hashes that appear in the proving, verification key filenames for the blockchain and transactions.

This PR partly addresses #1492 (nothing to do with Columbus or Isabella, I believe).

Text output:
```
coda.exe internal snark-hashes
1fcfafce88045da8edb21ca60f16364e
5cb02d2fce6f6865d9459434c8279373
791dd47158e4dad32059f8b6d5fef4e8
d54a391ecc01065ad98c490ec10fe56c
d7cee32fe1dccee1745b0c8cc6bbd3b8
```
JSON:
```
coda.exe internal snark-hashes -json
["1fcfafce88045da8edb21ca60f16364e","5cb02d2fce6f6865d9459434c8279373","791dd47158e4dad32059f8b6d5fef4e8","d54a391ecc01065ad98c490ec10fe56c","d7cee32fe1dccee1745b0c8cc6bbd3b8"]
```
There's meaningful output only at full proof level. Otherwise, the list of hashes is empty.

### CODE REVIEW

**Comment by bkase** [comment]
Any reason why you didn't use the `coda client list-required-keys` command?

**Comment by psteckler** [comment]
> Any reason why you didn't use the `coda client list-required-keys` command?

The use case is when the daemon can't even start because of missing keys.

**Comment by jkrauska** [comment]
> Any reason why you didn't use the `coda client list-required-keys` command?

Maybe you mean:
coda client constraint-system-digests
??

One problem is that it has never matched the actual keys on disk.

eg

```
admin@20190613_us-west-2_joiner_0:~$ coda client constraint-system-digests
blockchain-step be7f2f165a561905a4d3ab424b0efd0a
blockchain-wrap ef61ed2dcc2b308394d30e5adc982691
transaction-base        5cb02d2fce6f6865d9459434c8279373
transaction-merge       d54a391ecc01065ad98c490ec10fe56c
transaction-wrap        1ecfb90b894161f7a95da07fe02419ee
```

```
admin@20190613_us-west-2_joiner_0:~$ ls /var/lib/coda/ | xargs -l | cut -d '_' -f 1 | sort | uniq
20ce1bc0d7f678446e8cde3a11b7f224
2fa1cfa1a103e01a93a6c12cb6df4476
5cb02d2fce6f6865d9459434c8279373
5ee0a55153fb6a46f2e0e750b8526050
6ea5cf17245bceebcef73513a74a3075
943d5abe66ee108d3b48f9dca42687c0
be41cbe803132d35f046be149ab8777e
c8c8026b0782d37805e299bb5f1364f6
client
d54a391ecc01065ad98c490ec10fe56c
f2a50610242bc217767b476722d1ce2f
```

**Comment by Schmavery** [comment]
Nice -- it strikes me that there's no way to check which keys are for snarking and which are for verifying -- when we port this to graphql we might want to add that information (assuming it's not necessary in the cli right now, don't want to block this issue)

**Comment by jkrauska** [comment]
> Nice -- it strikes me that there's no way to check which keys are for snarking and which are for verifying -- when we port this to graphql we might want to add that information (assuming it's not necessary in the cli right now, don't want to block this issue)

Maybe you mean proving blocks or proving transactions?

Verifying keys are small and should always be grabbed. (<60kb)

**Pull request merged**
