### PR TITLE
Show status when you are Bootstrapping

### PR DESCRIPTION
**Pull request by johnwu93**
When you are bootstrapping, we would want to show specific metrics related to Bootstrapping and not show anything and throw an exception. In this PR, you can see your status while you are Bootstrapping if you run `coda client status`.

Here is what the status looks like when you are an active participant in the network:
```
Coda Daemon Status 
-----------------------------------

Sync status:                Active
Global Number of Accounts:  18
Block Count:                1
Local Uptime:               153s
Ledger Merkle Root:         44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908
Staged-ledger Hash:         ((ledger_hash 44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908)(aux_hash"\025\138\180\007\198$\240\129\248\254YgK+@\204@\026\147\202\172\179\030\006\180@s\179\202\170\250,0"))
Staged Hash:                124311839978739981459371389860110851594522793255731454918783662182772220850819819043777858
Configuration Directory:    /home/o1labs/.coda-config
Peers:                      Total: 0 ()
User_commands Sent:         0
Snark Worker Running:       false
Proposer Running:           false
Best Tip Consensus Time:    <posig has no notion of time>
Consensus Time Now:         2019-03-15 18:20:20.549266Z
Consensus Mechanism:        proof_of_signature
Consensus Configuration:    
    proposal_interval = 2000
``` 

Here is the json of that:
```
[                  
  "Active",
  {
    "num_accounts": 18,
    "block_count": 1,
    "uptime_secs": 43,
    "ledger_merkle_root":
      "44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908",
    "staged_ledger_hash":
      "((ledger_hash 44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908)(aux_hash\"\\025\\138\\180\\007\\198$\\240\\129\\248\\254YgK+@\\204@\\026\\147\\202\\172\\179\\030\\006\\180@s\\179\\202\\170\\250,0\"))",
    "state_hash":
      "124311839978739981459371389860110851594522793255731454918783662182772220850819819043777858",
    "commit_id": null,
    "conf_dir": "/home/o1labs/.coda-config",
    "peers": [],
    "user_commands_sent": 0,
    "run_snark_worker": false,
    "propose_pubkey": null,
    "histograms": null,
    "consensus_time_best_tip": "<posig has no notion of time>",
    "consensus_time_now": "2019-03-15 18:31:24.182235Z",
    "consensus_mechanism": "proof_of_signature",
    "consensus_configuration": { "proposal_interval": 2000 }
  }
]
```

Here is your status when you are Boostrapping:
```
Coda Daemon Status 
-----------------------------------

Sync status:              Bootstrapping
Local Uptime:             45s
Configuration Directory:  /home/o1labs/.coda-config
Peers:                    Total: 0 ()
User_commands Sent:       0
Snark Worker Running:     false
Proposer Running:         false
Consensus Mechanism:      proof_of_signature
Consensus Time Now:       2019-03-15 18:41:54.623842Z
Consensus Configuration:  
    proposal_interval = 2000

```

Here is the Json of that:

```
[                  
  "Bootstrapping",
  {
    "uptime_secs": 90,
    "commit_id": null,
    "conf_dir": "/home/o1labs/.coda-config",
    "peers": [],
    "user_commands_sent": 0,
    "run_snark_worker": false,
    "propose_pubkey": null,
    "histograms": null,
    "consensus_mechanism": "proof_of_signature",
    "consensus_time_now": "2019-03-15 18:42:40.074275Z",
    "consensus_configuration": { "proposal_interval": 2000 }
  }
]
```

For status, you can see rpc performance histograms while being Active or Bootstrapping. This demo omitted this.

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

**Comment by enolan** [comment]
Implementing sum types in JSON with an array is very non-standard. Do something like

```json
{
  "sync_status": "active",
  "num_accounts": 18
  etc
}
```

and

```json
{
  "sync_status": "bootstrapping",
  "uptime_secs": 90
  etc
}
```

And it'll be easier to process.

**Comment by jkrauska** [comment]
Text output:

Capitalize "Status" to be consistent with formatting.
Sync status:  --> Sync Status: 

JSON:
Don't make it an unlabled new top, instead include it INSIDE the dictionary.

From:
```
[                  
  "Bootstrapping",
  {
    "uptime_secs": 90,
    "commit_id": null,
```

To

```
[                  
  {
    "sync_status": "Bootstrapping",
    "uptime_secs": 90,
    "commit_id": null,
```

**Comment by jkrauska** [comment]
What's the enum of possible states?
What's the initial state?

The first one you listed has no blocks and no peers.  Are we sure that's 'Active'?

Maybe 'Disconnected' ?



Also during bootstrapping, you're not listing blocktime, accounts, etc.
Can you please still list them so we have consistent output.
Value 'NA' is better than not listing at all.

(People will write tools looking for things like block_count, etc.)

**Comment by johnwu93** [comment]
As per @jkrauska request, here are the changes:

Here is the status for a non-bootstrapping node
```
Coda Daemon Status 
-----------------------------------

Is Bootstrapping:           false
Global Number of Accounts:  18
Block Count:                1
Local Uptime:               4s
Ledger Merkle Root:         44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908
Staged-ledger Hash:         ((ledger_hash 44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908)(aux_hash"\025\138\180\007\198$\240\129\248\254YgK+@\204@\026\147\202\172\179\030\006\180@s\179\202\170\250,0"))
Staged Hash:                124311839978739981459371389860110851594522793255731454918783662182772220850819819043777858
Configuration Directory:    /home/o1labs/.coda-config
Peers:                      Total: 0 ()
User_commands Sent:         0
Snark Worker Running:       false
Proposer Running:           false
Best Tip Consensus Time:    <posig has no notion of time>
Consensus Time Now:         2019-03-15 21:34:53.905491Z
Consensus Mechanism:        proof_of_signature
Consensus Configuration:    
    proposal_interval = 2000
```

Here is it's json:
```
{                  
  "is_bootstrapping": false,
  "num_accounts": 18,
  "block_count": 1,
  "uptime_secs": 80,
  "ledger_merkle_root":
    "44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908",
  "staged_ledger_hash":
    "((ledger_hash 44118186185760405951351635805866215026781089753408405860411344948048965529848662642670908)(aux_hash\"\\025\\138\\180\\007\\198$\\240\\129\\248\\254YgK+@\\204@\\026\\147\\202\\172\\179\\030\\006\\180@s\\179\\202\\170\\250,0\"))",
  "state_hash":
    "124311839978739981459371389860110851594522793255731454918783662182772220850819819043777858",
  "commit_id": null,
  "conf_dir": "/home/o1labs/.coda-config",
  "peers": [],
  "user_commands_sent": 0,
  "run_snark_worker": false,
  "propose_pubkey": null,
  "histograms": null,
  "consensus_time_best_tip": "<posig has no notion of time>",
  "consensus_time_now": "2019-03-15 21:36:09.698255Z",
  "consensus_mechanism": "proof_of_signature",
  "consensus_configuration": { "proposal_interval": 2000 }
```

Here is the status of a bootstrapping node:
```
Coda Daemon Status 
-----------------------------------

Is Bootstrapping:         true
Local Uptime:             7s
Configuration Directory:  /home/o1labs/.coda-config
Peers:                    Total: 0 ()
User_commands Sent:       0
Snark Worker Running:     false
Proposer Running:         false
Consensus Time Now:       2019-03-15 21:38:20.593939Z
Consensus Mechanism:      proof_of_signature
Consensus Configuration:  
    proposal_interval = 2000

```

Here is it's Json:


```{                  
  "is_bootstrapping": true,
  "num_accounts": null,
  "block_count": null,
  "uptime_secs": 37,
  "ledger_merkle_root": null,
  "staged_ledger_hash": null,
  "state_hash": null,
  "commit_id": null,
  "conf_dir": "/home/o1labs/.coda-config",
  "peers": [],
  "user_commands_sent": 0,
  "run_snark_worker": false,
  "propose_pubkey": null,
  "histograms": null,
  "consensus_time_best_tip": null,
  "consensus_time_now": "2019-03-15 21:38:50.317594Z",
  "consensus_mechanism": "proof_of_signature",
  "consensus_configuration": { "proposal_interval": 2000 }
}

```

**Pull request merged**
