### PR TITLE
Added PM, CK, CY, MW, updated CS spelling

### PR DESCRIPTION
**Pull request by michellewong793**
Added 4 new team members, and updated spelling

### CODE REVIEW

**Comment by bkase** [comment]
Can you share on staging? Claire's bio may be too long

**Comment by michellewong793** [comment]
> Can you share on staging? Claire's bio may be too long
shared! & asked Claire to shorten bio

**Comment by michellewong793** [comment]
Shared on staging, waiting for shortened bio from Claire

**Comment by michellewong793** [comment]
Screen Shot 2019-09-18 at 3 52 16 PM

Pranay and I were investigating why the ş in Emre's name was smaller than the rest of the characters- turns out the way Pragmata Pro is rendering the capital ş  is much smaller than the other characters

**Comment by bkase** [comment]
I asked Claire to shorten her bio -- probably too long given the length of the others

**Comment by Schmavery** [comment]
build-wallet isn't required right now, but it's showing that refmt needs to be run (might not be due to this change but might as well)

**Pull request merged**
