### PR TITLE
[WIP] Dune contextual profile builds

### PR DESCRIPTION
**Pull request by nholland94**
This PR provides a new way for organizing profile builds underneath dune contexts. There is a new root level `dune-workspace` file which contains context entries for each build profile in our codebase (this file can be code generated with `scripts/generated_dune_workspace dune-workspace`). This allows each build profile to live in it's own build directory. Each context in dune has it's build artifacts organized under `_build/<context>`. In order to build in a certain context, you can issue a build command like `dune build _build/<context>/<target>`. This means that you can no longer just have dune do it's default behavior of building all installable targets while also selecting a specific context/profile. However, it does mean that build artifacts will be properly reused when switching between profiles.

Outstanding work:
- [ ] integrating code generation of root level `dune-workspace` into either git hooks or the `Makefile`
- [ ] integrating this method of interacting with build profiles into test and CI related scripts

### CODE REVIEW

**Comment by enolan** [comment]
This sounds great, but I'm not going to remember the paths to the different build targets. Can we have a shell script or something? Or I guess I could start using make.

**Comment by nholland94** [comment]
> This sounds great, but I'm not going to remember the paths to the different build targets. Can we have a shell script or something? Or I guess I could start using make.

I think adding a make entry is kind of a pain since you would need to set and pass an environment variable to change the profile. I personally dislike this workflow, so I would probably prefer a script. FWIW, the path remains mostly the same across different builds. All you need to do is just to swap out the context dir, which has the same name as the profile you want to build. So, `dune build _build/test_postake_snarkless/src/app/cli/src/coda.exe` vs. `dune build _build/test_postake_holy_grail/src/app/cli/src/coda.exe`.

**Comment by nholland94** [comment]
One specific thing I forgot to mention in the original description: this change will require everyone to create a `coda` opam switch. I chose to namespace the switch so that it is easier for developers to create isolated opam switches for different dependencies. I wish I could just let `dune` select the current opam switch from your environment, but it seems like `dune` does not support that while also supporting the ability to set different build names for contexts (very stupid, I know).

**Comment by nholland94** [comment]
Putting all of the contexts in one file was causing a lot of slow down in dune, so I have changed the pattern so that we have one workspace per build context and profile. Now, to dispatch builds, you will no longer need to give fully qualified artifact paths. To build a specific profile, now you just need to dispatch `dune build --workspace=dune-workspace.<profile>`.

**Pull request closed without merging**
