### PR TITLE
only run brew when needed

### PR DESCRIPTION
**Pull request by jkrauska**
Don't run brew when you don't need to. (previously ran with whitespace)

### CODE REVIEW

**Comment by cmr** [comment]
the script fix is good, but both of the `Not running compile step`/`Not running download step` will get printed in a typical `make macos-setup` invocation, right? I think that's confusing?

**Comment by jkrauska** [comment]
> the script fix is good, but both of the `Not running compile step`/`Not running download step` will get printed in a typical `make macos-setup` invocation, right? I think that's confusing?

True.  

mainly I was responding to the fact that with -x on, you get "[[ NO == \Y\E\S ]]" which isn't really helpful for context of what's being done.

I think the Makefile could also be changed from

macos-setup: macos-setup-download macos-setup-compile

to 
./scripts/macos-setup.sh compile all

??

**Comment by cmr** [comment]
Just `./scripts/macos-setup.sh all` I think. Do that change, and I'm happy with the additional echo.

**Comment by jkrauska** [comment]
@cmr all

**Pull request merged**
