### PR TITLE
Use affine pedersen params

### PR DESCRIPTION
**Pull request by imeckler**
This bumps snarky as to avoid converting the Pedersen generators to affine coordinates on the fly as we prove.

### CODE REVIEW

**Comment by mrmr1993** [comment]
Combined with o1-labs/snarky#309 I'm seeing a decent improvement:
```
$ `which time` dune exec coda -- tra -witness-only -repeat 10
53.53user 1.72system 0:55.99elapsed 98%CPU (0avgtext+0avgdata 214944maxresident)k
24048inputs+8360outputs (4major+724539minor)pagefaults 0swaps
$ `which time` dune exec coda -- tra -witness-only -repeat 10
53.91user 1.38system 0:55.19elapsed 100%CPU (0avgtext+0avgdata 206996maxresident)k
0inputs+8384outputs (0major+722964minor)pagefaults 0swaps
$ (cd ..; make benchmarks); BENCHMARK_LIBRARIES=vrf_lib_tests ../scripts/benchmarks.sh
INFO Not using Docker
cd src && dune build app/benchmarks/main.exe
Running inline tests in library "vrf_lib_tests"
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
┌──────────────────────────────────────────────────────────────────────┬──────────┬─────────────┬────────────┬────────────┬────────────┐
│ Name                                                                 │ Time/Run │     mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────┼──────────┼─────────────┼────────────┼────────────┼────────────┤
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │   1.25ms │     73.30kw │     4.47kw │     4.17kw │      0.28% │
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │ 439.60ms │ 20_731.45kw │ 6_899.16kw │ 6_898.35kw │    100.00% │
└──────────────────────────────────────────────────────────────────────┴──────────┴─────────────┴────────────┴────────────┴────────────┘
Benchmarks that take 1ns to 100ms can be estimated precisely. For more reliable
estimates, redesign your benchmark to have a shorter execution time.
$ (cd ..; make benchmarks); BENCHM
ARK_LIBRARIES=vrf_lib_tests ../scripts/benchmarks.sh
INFO Not using Docker
cd src && dune build app/benchmarks/main.exe
Running inline tests in library "vrf_lib_tests"
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
┌──────────────────────────────────────────────────────────────────────┬──────────┬─────────────┬────────────┬────────────┬────────────┐
│ Name                                                                 │ Time/Run │     mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────┼──────────┼─────────────┼────────────┼────────────┼────────────┤
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │   1.25ms │     73.30kw │     4.47kw │     4.17kw │      0.28% │
│ [lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │ 442.93ms │ 20_731.45kw │ 6_899.16kw │ 6_898.35kw │    100.00% │
└──────────────────────────────────────────────────────────────────────┴──────────┴─────────────┴────────────┴────────────┴────────────┘
Benchmarks that take 1ns to 100ms can be estimated precisely. For more reliable
estimates, redesign your benchmark to have a shorter execution time.
```

Ballpark 9% improvement, not quite as good as we were expecting, but still pretty nice.

**Comment by imeckler** [comment]
I'm not sure `dune exec coda -- tra -witness-only -repeat 10` is the right thing to run. It looked to me like it was spending a lot of its time evaluating and checking the constraints which we don't do in witness generation.

**Comment by mrmr1993** [comment]
I can turn off `eval_constraints` and run again? Might give a better indication.

**Comment by mrmr1993** [comment]
This PR + o1-labs/snarky#309 (`set_eval_constraints false` in `coda.ml`)
```
$ `which time` dune exec coda -- tra -witness-only -repeat 10
33.22user 1.60system 0:34.88elapsed 99%CPU (0avgtext+0avgdata 215272maxresident)k
0inputs+8384outputs (0major+466501minor)pagefaults 0swaps
$ `which time` dune exec coda -- tra -witness-only -repeat 10
33.73user 1.58system 0:35.25elapsed 100%CPU (0avgtext+0avgdata 214360maxresident)k
0inputs+8384outputs (0major+465227minor)pagefaults 0swaps
```
o1-labs/snarky#309 alone (`set_eval_constraints false` in `coda.ml`):
```
$ `which time` dune exec coda -- tra -witness-only -repeat 10
41.78user 1.90system 0:44.40elapsed 98%CPU (0avgtext+0avgdata 212400maxresident)k
23128inputs+8384outputs (1major+488341minor)pagefaults 0swaps
$ `which time` dune exec coda -- tra -witness-only -repeat 10
40.65user 2.23system 0:42.85elapsed 100%CPU (0avgtext+0avgdata 214908maxresident)k
0inputs+8384outputs (0major+488218minor)pagefaults 0swaps
```

------------------------------------

This PR + o1-labs/snarky#309 (`set_eval_constraints false` in `coda.ml` and `run_and_check` -> `run_unchecked` in `transaction_snark.ml`):

```
$ `which time` dune exec coda -- tra -witness-only -repeat 10
30.37user 1.35system 0:32.25elapsed 98%CPU (0avgtext+0avgdata 214392maxresident)k
27456inputs+8384outputs (6major+465557minor)pagefaults 0swaps
$ `which time` dune exec coda -- tra -witness-only -repeat 10
30.48user 1.14system 0:31.55elapsed 100%CPU (0avgtext+0avgdata 214352maxresident)k
0inputs+8384outputs (0major+465910minor)pagefaults 0swaps
```

o1-labs/snarky#309 alone (`set_eval_constraints false` in `coda.ml` and `run_and_check` -> `run_unchecked` in `transaction_snark.ml`):
```
$ `which time` dune exec coda -- tra -witness-only -repeat 10
40.24user 2.22system 0:42.87elapsed 99%CPU (0avgtext+0avgdata 215716maxresident)k
22160inputs+8384outputs (4major+489263minor)pagefaults 0swaps
$ `which time` dune exec coda -- tra -witness-only -repeat 10
41.45user 1.33system 0:42.70elapsed 100%CPU (0avgtext+0avgdata 214788maxresident)k
96inputs+8384outputs (0major+489144minor)pagefaults 0swaps
```

The improvement looks even better when constraint checking is disabled :grin:

**Comment by mrmr1993** [comment]
Closing, this was merged as part of #2911.

**Pull request closed without merging**
