### PR TITLE
generate 10k ledger

### PR DESCRIPTION
**Pull request by jkrauska**
Generate custom 10k ledger

### CODE REVIEW

**Comment by deepthiskumar** [comment]
We don't want 10k accounts as the default right? We should either have a different build target for medium curves profile that ci uses or have an env variable for the number of accounts?

**Comment by bkase** [comment]
@deepthiskumar I think we do want 10k as the default so we can make sure to keep testing at the limits

**Comment by jkrauska** [comment]
perhaps then a config option 
runtime_ledger_account_size
that is the default for the utility?

some tests won't want to use/see 10k acocunts. (may even have smaller ledger depth and not be able to use them at all)

**Comment by deepthiskumar** [comment]
Do we want this for dev as well? Also, we still don't know how this impacts the daemon, that's what we are going to test, right?

**Comment by deepthiskumar** [comment]
@jkrauska tests won't be impacted because they still use the compile time generated ledgers

**Comment by bkase** [comment]
oh right good point I guess we do want it different based on config

**Pull request merged**
